genesis-file="/config/genesis.json"
node-private-key-file="/opt/besu/keys/nodekey"
logging="INFO"
#logging="DEBUG"
#logging="trace"
data-path="/opt/besu/data"
host-allowlist=["*"]
min-gas-price=0

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# permissions
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/config/permissions_config.toml"

# bootnodes
bootnodes=["enode://73dc33c3649403d6d1a5499bf0da3acda9dc56ac6a5aa03dfdc6d34760a6ad49cb06c1abd3f2c0b4d2d3b8b57f225b1227820827fe7b6798f716dc8caf43c6a4@10.10.100.11:30303"]
#bootnodes=["enode://798fd1b9cd0bbf463079e102447ce91c5b9d8244cc208402f0ae2438d491781547f26b97c60795f9ae777bcecd462583808d0d975601eb0bf262235813fa3c89@10.10.100.11:30303"]


# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
static-nodes-file="/config/static-nodes.json"
discovery-enabled=true

# rpc
rpc-http-api = ["ETH", "NET", "WEB3" , "ADMIN", "DEBUG", "MINER" ]
