nodes-allowlist=[
"enode://73dc33c3649403d6d1a5499bf0da3acda9dc56ac6a5aa03dfdc6d34760a6ad49cb06c1abd3f2c0b4d2d3b8b57f225b1227820827fe7b6798f716dc8caf43c6a4@10.10.100.11:30303",
"enode://b9f13ad5d6ae1efc3d70dd577ed4f78c4c2dfbf4e619c85227fff85bc826f729b1d23e60fc4e6924c769ebe136b56ef946d8760583a7fa3af8ee7696ed5e1e2e@10.10.100.12:30303",
"enode://5848445acb76e92a3c3cd035d16fefa4820fd18be587666e4ed5d9d0946868740224d192e4a36b1e46d3d433883929e2f2bf6906d296bf2001e0d6ca8d2f7853@10.10.100.13:30303",
"enode://9aea213e6491834c55a07f83362bc249c39607ba99381e61ac247eaf77ea61ca2699c38efd2bd6bd4fa71f8ac8c70a08da97f72620f2db2aa75089b727a25a47@10.10.100.15:30303"
]